config/routes.rb
Rails.application.routes.draw do
  root 'apps_pages#index'

  namespace :admin do
    resources :config, only: %i[], path: '/' do
      put '/', on: :collection, action: :update, as: :update
      get '/', on: :collection, action: :edit
    end
  end
end

app/models/app.rb
class App
  include ActiveModel::Validations
  include Concerns::ModelBase

  attr_accessor :id, :name, :category, :position, :url

  validates :name, :category, :position, :url, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apps_page.rb
class AppsPage < ApplicationRecord
  default_scope { where('created_at < ?', ConfigService.get_config.max_date) }
end

app/models/concerns/model_base.rb
module Concerns
  module ModelBase
    extend ActiveSupport::Concern

    included do
      def initialize(attributes = {})
        attributes.each do |name, value|
          send("#{name}=", value)
        end
      end
    end
  end
end

app/models/config.rb
class Config
  include ActiveModel::Validations

  attr_accessor :analyse_every, :max_date

  validates :analyse_every, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :max_date, presence: true

  def initialize(analyse_every:, max_date:)
    @analyse_every = analyse_every
    @max_date = DateTime.parse(max_date)
  end
end

app/controllers/admin/config_controller.rb
module Admin
  class ConfigController < ApplicationController

    def edit
      @config = ConfigService.get_config
    end

    def update
      @config = Config.new(permited_params)
      if @config.valid?
        ConfigService.set_config(permited_params)
        redirect_to :root
      else
        render :edit
      end
    end

    private

    def permited_params
      params.require(:config).permit(:analyse_every, :max_date).to_h.symbolize_keys
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/apps_pages_controller.rb
class AppsPagesController < ApplicationController
  include AppsPagesHelper

  def index
    if params[:version]
      app_page = AppsPage.find_by(id: params[:version])
    else
      app_page= AppsPage.last
    end
    @apps_categories =  parse_json(app_page)
    @versions = AppsPage.all || []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_pages_helper.rb
module AppsPagesHelper
  def parse_json(state)
    return [] unless state
    JSON.parse(state.page_state).map do |json_app|
      App.new(json_app)
    end.group_by(&:category)
  end
end

app/views/admin/config/edit.html.haml
%h1 Admin Area
- if @config.errors
  %ul.errors
    - @config.errors.full_messages.each do |msg|
      %li= msg
= simple_form_for :config, url: update_admin_config_index_path, method: :put do |f|
  = f.input :analyse_every, as: :numeric
  = f.input :max_date, as: :datetime, html5: true
  = f.submit

app/views/apps_pages/index.html.haml
%h1
  .dropdown
    %button.btn.btn-primary.dropdown-toggle{href: "#", "role" => "button", "data-toggle" => "dropdown"}
      Version
      %span.caret
    %ul.dropdown-menu
      - @versions.each do |version|
        %li
          = link_to version.created_at.localtime, root_path(version: version.id)
%h2
  - @apps_categories.each do |category, apps|
    %h2
      = category
    %table.table.table-striped.table-bordered.table-hover.table-condensed
      %thead
        %tr
          %th Name
          %th Position
          %th Link
      %tbody
        - apps.each do |app|
          %tr
            %td.col-md-4
              = app.name
            %td.col-md-1
              = app.position
            %td.col-md-4
              = link_to app.url, app.url, target: :_blank

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ShopifyApps
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .navbar.navbar-inverse
      .navbar-header
        = link_to 'Shopify Apps', root_path, class: 'navbar-brand'
      .navbar-right
        = link_to 'Admin Zone', admin_config_index_path, class: 'navbar-brand'
    = yield